# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "master",
        "doc_baseurl": "/archive",
        "doc_host": "https://dotpyo.github.io",
        "git_url": "https://github.com/dotpyo/archive",
        "lib_path": "archive",
    },
    "syms": {
        "archive.core": {"archive.core.foo": ("core.html#foo", "archive/core.py")}
    },
}
