# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/archive',
                'doc_host': 'https://4923.github.io',
                'git_url': 'https://github.com/4923/archive',
                'lib_path': 'archive'},
  'syms': {'archive.core': {'archive.core.foo': ('core.html#foo', 'archive/core.py')}}}
