# ./git lonbs/_quarto.yml

project:
  type: website

execute:
  echo: true

format:
  html:
    # page-layout: full
    # https://bootswatch.com/
    theme:
      light: sandstone
      dark: darkly
    css: styles.css
    toc: true
    
    # ====
    # CODE
    # ====
    
    # https://quarto.org/docs/output-formats/html-code.html#code-overflow
    code-overflow: scroll
    # https://quarto.org/docs/output-formats/html-code.html#code-tools
    code-fold: true   
    code-tools: true
    # https://quarto.org/docs/output-formats/html-code.html#line-numbers
    highlight-style: github
    code-line-numbers: false
    code-block-background: true
    code-copy: hover
# https://quarto.org/docs/output-formats/html-code.html#highlighting
# Quarto will automatically select the appropriate style based upon the code chunk background color’s darkness. 
# Users may always opt to specify the full name (e.g. atom-one-dark) to by pass this automatic behavior.


metadata-files: [nbdev.yml, sidebar.yml]

website:
  reader-mode: false
  # navbar:
  #   background: primary
  #   search: true
  google-analytics: "G-SRFKSE5H0V"

  sidebar:            # https://quarto.org/docs/websites/website-navigation.html#side-navigation 
    style: floating
    search: true
    navbar: false # Hides the navbar on this page
    contents: auto    # https://quarto.org/docs/websites/website-navigation.html#auto-generation
    tools:
      - icon: person-circle
        href: https://4923.github.io/archive/CV.html
      - icon: github
        href: https://github.com/4923

  favicon: favicon.ico
  comments: 
    utterances:
      repo: 4923/archive
  repo-actions: [issue]

  page-navigation: true

  page-footer: 
    center: "Copyright 2023, YeEun Hong" 
    