# ./git lonbs/_quarto.yml

project:
  type: website

execute:
  echo: true

format:
  html:
    # https://bootswatch.com/sketchy/
    theme:
      light: lux
      dark: superhero
    css: styles.css
    toc: true
    # https://quarto.org/docs/output-formats/html-code.html#code-overflow
    code-overflow: "wrap"
    # https://quarto.org/docs/output-formats/html-code.html#code-tools
    code-fold: true   
    code-tools: true
    # https://quarto.org/docs/output-formats/html-code.html#line-numbers
    code-line-numbers: false
    code-block-border-left: true
# https://quarto.org/docs/output-formats/html-code.html#highlighting
# Quarto will automatically select the appropriate style based upon the code chunk background color’s darkness. 
# Users may always opt to specify the full name (e.g. atom-one-dark) to by pass this automatic behavior.


metadata-files: [nbdev.yml, sidebar.yml]

website:  
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  
  navbar:
    background: primary
    search: true

  sidebar:            # https://quarto.org/docs/websites/website-navigation.html#side-navigation 
    style: floating
    search: true
    contents: auto    # https://quarto.org/docs/websites/website-navigation.html#auto-generation
  