# ./git lonbs/_quarto.yml

project:
  type: website

# Freezing Computations
# To make sure that R, Python, and Julia code is only executed locally, configure your project to use Quarto’s freeze feature by adding this to your _quarto.yml:
execute:
  freeze: auto
    
format:
  html:
    # [ 주의 ] 이미지 확장자 제거
    # (240309) github issue 에 이미지를 호스팅해오는 과정을 거쳤었는데 이 경우 html 렌더링 과정에서 `.png`가 자동으로 붙는다.
    # 해당 문제를 해결하기 위해 이미지 확장자를 자동으로 붙이는 기능을 제거했지만 권고할만한 사항은 아니라고 한다.
    # https://github.com/quarto-dev/quarto-cli/issues/6092
    default-image-extension: ""

    # header
    include-in-header: 
      # - text: <meta name="referrer" content="strict-origin-when-cross-origin" >
      - file: header.html

    # font
    fontsize: 1.2rem
    linestretch: 2
    whitespace: 200rem
    section-divs: true

    # math
    html-math-method: mathjax
    classoption: fleqn

    # table of contents
    toc: true
    toc-depth: 4
    toc-location: right
    strip-comments: false

    # code
    highlight-style: github
    code-overflow: scroll   # https://quarto.org/docs/output-formats/html-code.html#code-overflow
    code-fold: false    # https://quarto.org/docs/output-formats/html-code.html#code-tools
    code-tools: true
    code-line-numbers: true   # https://quarto.org/docs/output-formats/html-code.html#line-numbers
    code-block-background: true
    code-copy: hover

    # layout
    page-layout: full # article
    theme:  # https://bootswatch.com/
      light: flatly
      dark: darkly
    css: styles.css
    title-block-style: default
    title-block-banner: true
    # "#003B68"
    title-block-categories: true

    # grid: 
    #   sidebar-width: 300px
    #   body-width: 900px
    #   margin-width: 200px
    #   gutter-width: 3rem
    
# https://quarto.org/docs/output-formats/html-code.html#highlighting
# Quarto will automatically select the appropriate style based upon the code chunk background color’s darkness. 
# Users may always opt to specify the full name (e.g. atom-one-dark) to by pass this automatic behavior.


metadata-files: [nbdev.yml] #, sidebar.yml]

website:
  # base
  title: "archive"
  google-analytics: 
    tracking-id: "G-L5Y3XFBP62"
  # site
  site-url: 'https://dotpyo.github.io/archive'
  site-path: '/'
  # features
  reader-mode: false
  # back-to-top-navigation: true
  bread-crumbs: false
  navbar:
    background: primary
    # search: true
    tools:
      - icon: person-circle
        href: CV.ipynb
      - icon: github
        href: https://github.com/dotpyo

  # sidebar:          # https://quarto.org/docs/websites/website-navigation.html#side-navigation 
  #   contents: auto    # https://quarto.org/docs/websites/website-navigation.html#auto-generation
  #   style: floating
  #   # border: true
  #   collapse-level: 2
  #   # search: true
  #   navbar: false # Hides the navbar on this page

  favicon: favicon.ico
  
  # comments: 
  #   utterances:
  #     repo: dotpyo/archive

  repo-actions: [issue]
  page-navigation: false

# Footnotes
reference-location: block     # [document | section | block | margin ]
# citation-location: margin   # [document | margin ]
callout-appearance: simple

author: 
    name: dotpyo
    email: 4923.py@gmail.com
# date: last-modified
