# ./git lonbs/_quarto.yml

project:
  type: website

# Freezing Computations
# To make sure that R, Python, and Julia code is only executed locally, configure your project to use Quarto’s freeze feature by adding this to your _quarto.yml:
execute:
  freeze: auto

format:
  html:
    page-layout: article
    # https://bootswatch.com/
    theme:
      light: flatly
      # dark: darkly
    css: styles.css
    toc: true
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 200px
      gutter-width: 3rem
    
    # https://quarto.org/docs/output-formats/html-code.html#code-overflow
    code-overflow: scroll
    # https://quarto.org/docs/output-formats/html-code.html#code-tools
    code-fold: false   
    code-tools: true
    # https://quarto.org/docs/output-formats/html-code.html#line-numbers
    highlight-style: github
    code-line-numbers: false
    code-block-background: true
    code-copy: hover
# https://quarto.org/docs/output-formats/html-code.html#highlighting
# Quarto will automatically select the appropriate style based upon the code chunk background color’s darkness. 
# Users may always opt to specify the full name (e.g. atom-one-dark) to by pass this automatic behavior.


metadata-files: [nbdev.yml] #, sidebar.yml]

website:
  # base
  title: "archive"
  google-analytics: 
    tracking-id: "G-L5Y3XFBP62"
  # site
  site-url: 'https://dotpyo.github.io/archive'
  site-path: '/'
  # features
  reader-mode: false
  # back-to-top-navigation: true
  bread-crumbs: false
  navbar:
    background: primary
    # search: true
    tools:
      - icon: person-circle
        href: CV.ipynb
      - icon: github
        href: https://github.com/dotpyo

  # sidebar:            # https://quarto.org/docs/websites/website-navigation.html#side-navigation 
  #   contents: auto    # https://quarto.org/docs/websites/website-navigation.html#auto-generation
  #   style: floating
  #   border: true
  #   collapse-level: 1
  #   # search: true
  #   navbar: false # Hides the navbar on this page

  favicon: favicon.ico
  
  # comments: 
  #   utterances:
  #     repo: dotpyo/archive

  repo-actions: [issue]
  page-navigation: false

# reference-location: margin
# citation-location: margin
callout-appearance: simple

