name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

# https://docs.github.com/en/actions/deployment/about-deployments/deploying-with-github-actions
concurrency: production

on:
  push:
    branches:
      [ "main", "master" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # every step must define a `uses` or `run` key
      # uses나 run만 있는 경우가 있어서 뭔가 했더니 이것 때문이었음
        # - https://github.com/einaregilsson/beanstalk-deploy/issues/2#issuecomment-555894644
      - name: deploy
        # using exist uses example
        uses: fastai/workflows/quarto-ghp@master
