name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

# https://docs.github.com/en/actions/deployment/about-deployments/deploying-with-github-actions
concurrency: production

on:
  push:
    branches:
      [ "main", "master" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
      # every step must define a `uses` or `run` key
      - uses: actions/checkout@v4
